### ISSUE TITLE
Disfetch in MSYS2 creates errors

### ISSUE THREAD

**Issue by temac000** [q60/disfetch#15]
Error:
```
ps: unknown option -- o
Try `ps --help' for more information.
```

Screenshot:
![image](https://user-images.githubusercontent.com/46126263/155345179-3ce1d920-c3dd-476c-ab29-1209b3fca145.png)

**Comment by begss** [comment]
[According to POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/), `ps` utility **must** have `-o` option.
