### ISSUE TITLE
NixOS Wallpaper?

### ISSUE THREAD

**Issue by AltF02** [q60/disfetch#4]
Hey, I was wondering if you could provide the nixos wallpaper found in the examples. Cheers 😄

**Comment by q60** [comment]
> Hey, I was wondering if you could provide the nixos wallpaper found in the examples. Cheers smile

i tried to find it... https://github.com/NixOS/nixos-artwork/blob/master/wallpapers/nix-wallpaper-nineish-dark-gray.png
